function flag=isavariable(finfo,varnum)
      % flags the variables in the file

          if strcmp(finfo.Variables(varnum).Attributes(1).Value,'method of data processing')||...
              strcmp(finfo.Variables(varnum).Attributes(1).Value,'Latitude of each location')||...
              strcmp(finfo.Variables(varnum).Attributes(1).Value,'time')||...
              strcmp(finfo.Variables(varnum).Attributes(1).Value,'Longitude of each location')||...
              strcmp(finfo.Variables(varnum).Attributes(1).Value,'quality flag')||...
              strcmp(finfo.Variables(varnum).Attributes(1).Value,'Depth of each measurement')||...
              strcmp(finfo.Variables(varnum).Attributes(1).Value,'Location unique identifier in data centre')||...
              strcmp(finfo.Variables(varnum).Attributes(1).Value,'Positioning system')||...
              strcmp(finfo.Variables(varnum).Attributes(1).Value,'Station/Location unique identifier in data centre')
         
            flag=0;
          else
            flag=1;
          end